const maps = [
	[ [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [] ],
	[ [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [] ],
	[ [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [] ],
	[ [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [] ],
	[ [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [] ],
	[ [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [] ],
	[ [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [] ],
	[ [], [], [], [], [], [], [],
	[
		'xxxxxxx^^xxxxxxx',
		'xxxxcx   xxxxxxx',
		'xxx      xxxxxxx',
		'xx       xxxxxxx',
		'x         xxxxxx',
		'<              >',
		'x             xx',
		'xx            xx',
		'xx            xx',
		'xxxxxxxxxxxxxxxx',
		'xxxxxxxxxxxxxxxx'
	],
	[
		'xxu^u^u^^u^u^u^u',
		'xxu u u  u u u u',
		'xx             >',
		'x     u  u u u >',
		'x u uo    o    >',
		'<     u  u u u >',
		'x u so    o    >',
		'x     u  u u u >',
		'xx             >',
		'xxuuuuuuuuuuuuuu',
		'xxuuuuuuuuuuuuuu'
	],
	[
		'wwwwwwwwwwwwwwww',
		'wwwwww  wwwwwwww',
		'< wwww       www',
		'<  www       www',
		'<   ww   b    ww',
		'<    w  bsb    >',
		'<        b    ww',
		'<            www',
		'<    w       www',
		'wwwwww  wwwwwwww',
		'wwwwwwwwwwwwwwww'
	],
	[
		'wwwwwwwwwwwwwwww',
		'wwwww w  wwwwwww',
		'wwwww     wwwwww',
		'wwww      wwwwww',
		'w w        w w w',
		'<              >',
		'w w        w w w',
		'wwww      wwwwww',
		'wwwww     wwwwww',
		'wwwww w  wwwwwww',
		'wwwwwwwwwwwwwwww'
	],
	[
		'wwwwwwwwwww^^^ww',
		'wwwwwwwwwcw   ww',
		'wwwwwww        >',
		'wwwwww         >',
		'ww ww          >',
		'<              >',
		'ww ww  aaaaaaaaa',
		'wwwwww aaaaaaaaa',
		'wwwwwwwaaaaaaaaa',
		'wwwwwwwaaaaaaaaa',
		'wwwwwwwaaaaaaaaa'
	], [], [], [], [] ]
]
