const maps = [
	[ [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [] ],
	[ [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [] ],
	[ [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [] ],
	[ [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [] ],
	[ [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [] ],
	[ [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [] ],
	[ [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [] ],
	[ [], [], [], [], [], [], [],
	[
		'xxxxxxx^^xxxxxxx',
		'xxxxcx   xxxxxxx',
		'xxx      xxxxxxx',
		'xx       xxxxxxx',
		'x         xxxxxx',
		'<              >',
		'x             xx',
		'xx            xx',
		'xx            xx',
		'xxxxxxxxxxxxxxxx',
		'xxxxxxxxxxxxxxxx'
	],
	[
		'xxu^u^u^^u^u^u^u',
		'xxu u u  u u u u',
		'xx             >',
		'x     u  u u u >',
		'x u uo    o    >',
		'<     u  u u u >',
		'x u co    o    >',
		'x     u  u u u >',
		'xx             >',
		'xxuuuuuuuuuuuuuu',
		'xxuuuuuuuuuuuuuu'
	],
	[
		'wwwwwwwwwwwwwwww',
		'wwwwww  wwwwwwww',
		'< wwww       www',
		'<  www       www',
		'<   ww   b    ww',
		'<    w  b b    >',
		'<        b    ww',
		'<            www',
		'<    w       www',
		'wwwwww  wwwwwwww',
		'wwwwwwwwwwwwwwww',
	],
	[], [], [], [], [], [] ]
]
