const maps = [
	[ [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [] ],
	[ [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [] ],
	[ [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [] ],
	[ [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [] ],
	[ [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [] ],
	[ [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [] ],
	[ [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [] ],
	[
		[
			'wwwwwwwwwwwwwwww',
			'wwwwwwwwwwwcwwww',
			'wwww           >',
			'www  tt tt     >',
			'ww   tt tt     >',
			'w              >',
			'ww    tt tt    >',
			'www   tt tt    >',
			'wwww           >',
			'wwwwwwwwwwwwwwww',
			'wwwwwwwwwwwwwwww'
		],
		[
			'wwwwwwwwww  wwww',
			'www  wwww    www',
			'<             ww',
			'<              w',
			'<              >',
			'<              >',
			'<              >',
			'<              w',
			'<             ww',
			'wwwwwwwwwwwwwwww',
			'wwwwwwwwwwwwwwww'
		],
		[
			'tttttt^^tttttttt',
			'tttttt  tttttttt',
			'tttttt         >',
			'tttttttttttttttt',
			'< tttttttttttttt',
			'<     tttttttttt',
			'<     tttttttttt',
			'tt    tttttttttt',
			'tt             >',
			'tttttttttttttttt',
			'tttttttttttttttt'
		],
		[
			'ttttttt^^^t^t^tt',
			'ttttttt   t t tt',
			'<             tt',
			'ttttttt        t',
			'ttttttt        >',
			'ttttttt   t    >',
			'ttttttt        >',
			'ttttttt        t',
			'<             tt',
			'tttttttttttttttt',
			'tttttttttttttttt'
		],
		[], [], [],
		[
			'xxxxxxx^^xxxxxxx',
			'xxxxcx   xxxxxxx',
			'xxx      xxxxxxx',
			'xx       xxxxxxx',
			'x         xxxxxx',
			'<              >',
			'x             xx',
			'xx            xx',
			'xx            xx',
			'xxxxxxxxxxxxxxxx',
			'xxxxxxxxxxxxxxxx'
		],
		[
			'xxu^u^u^^u^u^u^u',
			'xxu u u  u u u u',
			'xx             >',
			'x     u  u u u >',
			'x u uo    o    >',
			'<     u  u u u >',
			'x u so    o    >',
			'x     u  u u u >',
			'xx             >',
			'xxuuuuuuuuuuuuuu',
			'xxuuuuuuuuuuuuuu'
		],
		[
			'wwwwwwwwwwwwwwww',
			'wwwwww  wwwwwwww',
			'< wwww       www',
			'<  www       www',
			'<   ww   b    ww',
			'<    w  bsb    >',
			'<        b    ww',
			'<            www',
			'<    w       www',
			'wwwwww  wwwwwwww',
			'wwwwwwwwwwwwwwww'
		],
		[
			'wwwwwwwwwwwwwwww',
			'wwwww w  wwwwwww',
			'wwwww     wwwwww',
			'wwww      wwwwww',
			'w w        w w w',
			'<              >',
			'w w        w w w',
			'wwww      wwwwww',
			'wwwww     wwwwww',
			'wwwww w  wwwwwww',
			'wwwwwwwwwwwwwwww'
		],
		[
			'wwwwwwwwwww^^^ww',
			'wwwwwwwwwcw   ww',
			'wwwwwww        >',
			'wwwwww         >',
			'ww ww          >',
			'<              >',
			'ww ww  aaaaaaaaa',
			'wwwwww aaaaaaaaa',
			'wwwwwwwaaaaaaaaa',
			'wwwwwwwaaaaaaaaa',
			'wwwwwwwaaaaaaaaa'
		],
		[
			'wwwwwwwwwwwwwwww',
			'wwwwwwwwwwwwwwww',
			'<              >',
			'<              >',
			'<              >',
			'<              >',
			'aaaaaaaaaaaaaaaa',
			'aaaaaaaaaaaaaaaa',
			'aaaaaaaaaaaaaaaa',
			'aaaaaaaaaaaaaaaa',
			'aaaaaaaaaaaaaaaa'
		],
		[
			'wwwwwwwwwwwwwwww',
			'wwwwwwwwwwwwwwww',
			'<              >',
			'<              >',
			'<              >',
			'<              >',
			'aaaaaaaaaaaaaaaa',
			'aaaaaaaaaaaaaaaa',
			'aaaaaaaaaaaaaaaa',
			'aaaaaaaaaaaaaaaa',
			'aaaaaaaaaaaaaaaa'
		],
		[
			'wwwwwwwwwwwwwwww',
			'wwwwwwwwwwwwwwww',
			'< wwwwwwwwwwwwww',
			'<  w  www  w  w>',
			'<              >',
			'<              >',
			'aaaaaaaaaaaaaaaa',
			'aaaaaaaaaaaaaaaa',
			'aaaaaaaaaaaaaaaa',
			'aaaaaaaaaaaaaaaa',
			'aaaaaaaaaaaaaaaa'
		],
		[
			'wwwww^^^^aaaaaaa',
			'wwwww    aaaaaaa',
			'wwwww    aaaaaaa',
			'< ww     aaaaaaa',
			'<        aaaaaaa',
			'<        aaaaaaa',
			'aaaaaaaaaaaaaaaa',
			'aaaaaaaaaaaaaaaa',
			'aaaaaaaaaaaaaaaa',
			'aaaaaaaaaaaaaaaa',
			'aaaaaaaaaaaaaaaa'
		]
	]
]
