const overworld = [
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<awwwwwwwwwwwwwwa>',
			'<awwwwwwwwwwwwwwa>',
			'<aw            wa>',
			'<aw ww www ww  wa>',
			'<aw ww wcw ww  wa>',
			'<aw             e>',
			'<aw  ww   ww   wa>',
			'<aw  ww   ww   wa>',
			'<aw            wa>',
			'<awwwwwwwwwwwwwwa>',
			'<awwwwwwwwwwwwwwa>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<aaaaaaa  ttttttt>',
			'<aaaaaaa  ttttttt>',
			'<aaaaaaa   t    t>',
			'<aaaaaaa        t>',
			'<aaaaaaa     t  t>',
			'<eeeeeee        t>',
			'<aaaaaaa     t  t>',
			'<aaaaaaa        t>',
			'<aaaaaaa   t    t>',
			'<aaaaaaa  ttttttt>',
			'<aaaaaaa  ttttttt>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<aaaaaaa  uuuuuuu>',
			'<aaaaaaa  uuuuuuu>',
			'<aaaaaaa      uuu>',
			'<aaaaaaa      uuu>',
			'<aaaaaaa      uuu>',
			'<             uuu>',
			'<             uuu>',
			'<uuu          uuu>',
			'<uuu          uuu>',
			'<uuuuuuu  uuuuuuu>',
			'<uuuuuuu  uuuuuuu>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<uuuuuuu  uuuuuuu>',
			'<uuuuuuu  uuuuuuu>',
			'<               u>',
			'<u u   u  u u   u>',
			'<                >',
			'<u u u u  u u u  >',
			'<                >',
			'<u u   u  u u   u>',
			'<               u>',
			'<uuu u u  u u u u>',
			'<uuu u u  u u u u>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxu u u  u u u u>',
			'<xxu u u  u u u u>',
			'<xx             u>',
			'<x   u    u   u u>',
			'<  u             >',
			'<    u u  u u u  >',
			'<  u             >',
			'<x   u    u   u u>',
			'<xx             u>',
			'<xxu u u  u u u u>',
			'<xxu u u  u u u u>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<wwwwwwwwwwwwwwww>',
			'<wwwwwwwwwwwcwwww>',
			'<wwww            >',
			'<www  tt tt      >',
			'<ww   tt tt      >',
			'<w               >',
			'<ww    tt tt     >',
			'<www   tt tt     >',
			'<wwww            >',
			'<wwwwwwwwwwwwwwww>',
			'<wwwwwwwwwwwwwwww>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<wwwwwwwwww  wwww>',
			'<www  wwww    www>',
			'<              ww>',
			'<               w>',
			'<                >',
			'<                >',
			'<                >',
			'<               w>',
			'<              ww>',
			'<wwwwwwwwwwwwwwww>',
			'<wwwwwwwwwwwwwwww>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<tttttt  tttttttt>',
			'<tttttt  tttttttt>',
			'<tttttt          >',
			'<tttttttttttttttt>',
			'<  tttttttttttttt>',
			'<      tttttttttt>',
			'<      tttttttttt>',
			'<tt    tttttttttt>',
			'<tt              >',
			'<tttttttttttttttt>',
			'<tttttttttttttttt>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<ttttttt   t t tt>',
			'<ttttttt   t t tt>',
			'<              tt>',
			'<ttttttt        t>',
			'<ttttttt         >',
			'<ttttttt   t     >',
			'<ttttttt         >',
			'<ttttttt        t>',
			'<              tt>',
			'<tttttttttttttttt>',
			'<tttttttttttttttt>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxxxxxxxxxxx>',
			'<xxxxxxxxxxxxxxxx>',
			'<xx            xx>',
			'<x      www     x>',
			'<    r rwcwr r  x>',
			'<               x>',
			'<    r r   r r  x>',
			'<x              x>',
			'<xx            xx>',
			'<xxxxxxxxxxxxxxxx>',
			'<xxxxxxxxxxxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxx aaxxxxxxxxx>',
			'<xxcx aaxxxxxxxxx>',
			'<xx   aa         >',
			'<x    aa d   d   >',
			'<x    aa   d     >',
			'<x  d aa d   d   >',
			'<x    aa   d     >',
			'<x    aa d   d   >',
			'<xx   aa         >',
			'<xxxxxaaxxxxxxxxx>',
			'<xxxxxaaxxxxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxxxxxxx  xx>',
			'<xxxxxxxxxxxx  xx>',
			'<              xx>',
			'<        d     xx>',
			'<          d    x>',
			'<  d  d  d       >',
			'<          d    x>',
			'<        d     xx>',
			'<              xx>',
			'<xxxxxxxxxxxxxxxx>',
			'<xxxxxxxxxxxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<xxxxcx   xxxxxxx>',
			'<xxx      xxxxxxx>',
			'<xx       xxxxxxx>',
			'<x         xxxxxx>',
			'<                >',
			'<x             xx>',
			'<xx            xx>',
			'<xx            xx>',
			'<xxxxxxxxxxxxxxxx>',
			'<xxxxxxxxxxxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxu u u  u u u u>',
			'<xxu u u  u u u u>',
			'<xx              >',
			'<x     u  u u u  >',
			'<x u uo    o     >',
			'<      u  u u u  >',
			'<x u so    o     >',
			'<x     u  u u u  >',
			'<xx              >',
			'<xxuuuuuuuuuuuuuu>',
			'<xxuuuuuuuuuuuuuu>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<wwwwwwwwwwwwwwww>',
			'<wwwwww  wwwwwwww>',
			'<  wwww       www>',
			'<   www       www>',
			'<    ww   b    ww>',
			'<     w  bsb     >',
			'<         b    ww>',
			'<             www>',
			'<     w       www>',
			'<wwwwww  wwwwwwww>',
			'<wwwwwwwwwwwwwwww>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<wwwwwwwwwwwwwwww>',
			'<wwwww w  wwwwwww>',
			'<wwwww     wwwwww>',
			'<wwww      wwwwww>',
			'<w w        w w w>',
			'<                >',
			'<w w        w w w>',
			'<wwww      wwwwww>',
			'<wwwww     wwwwww>',
			'<wwwww w  wwwwwww>',
			'<wwwwwwwwwwwwwwww>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<wwwwwwwwwww   ww>',
			'<wwwwwwwwwcw   ww>',
			'<wwwwwww         >',
			'<wwwwww          >',
			'<ww ww           >',
			'<                >',
			'<ww ww  aaaaaaaaa>',
			'<wwwwww aaaaaaaaa>',
			'<wwwwwwwaaaaaaaaa>',
			'<wwwwwwwaaaaaaaaa>',
			'<wwwwwwwaaaaaaaaa>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<wwwwwwwwwwwwwwww>',
			'<wwwwwwwwwwwwwwww>',
			'<                >',
			'<                >',
			'<                >',
			'<                >',
			'<aaaaaaaaaaaaaaaa>',
			'<aaaaaaaaaaaaaaaa>',
			'<aaaaaaaaaaaaaaaa>',
			'<aaaaaaaaaaaaaaaa>',
			'<aaaaaaaaaaaaaaaa>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<wwwwwwwwwwwwwwww>',
			'<wwwwwwwwwwwwwwww>',
			'<                >',
			'<                >',
			'<                >',
			'<                >',
			'<aaaaaaaaaaaaaaaa>',
			'<aaaaaaaaaaaaaaaa>',
			'<aaaaaaaaaaaaaaaa>',
			'<aaaaaaaaaaaaaaaa>',
			'<aaaaaaaaaaaaaaaa>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<wwwwwwwwwwwwwwww>',
			'<wwwwwwwwwwwwwwww>',
			'<  wwwwwwwwwwwwww>',
			'<   w  www  w  w >',
			'<                >',
			'<                >',
			'<aaaaaaaaaaaaaaaa>',
			'<aaaaaaaaaaaaaaaa>',
			'<aaaaaaaaaaaaaaaa>',
			'<aaaaaaaaaaaaaaaa>',
			'<aaaaaaaaaaaaaaaa>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<wwwww    aaaaaaa>',
			'<wwwww    aaaaaaa>',
			'<wwwww    aaaaaaa>',
			'<  ww     aaaaaaa>',
			'<         aaaaaaa>',
			'<         aaaaaaa>',
			'<aaaaaaaaaaaaaaaa>',
			'<aaaaaaaaaaaaaaaa>',
			'<aaaaaaaaaaaaaaaa>',
			'<aaaaaaaaaaaaaaaa>',
			'<aaaaaaaaaaaaaaaa>',
			'vvvvvvvvvvvvvvvvvv'
		]
	]
]
