let maps2 = [
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x  x  x  x  x  x>',
			'<x              x>',
			'<   x  x  x  x   >',
			'<x              x>',
			'<x  x  x  x  x  x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	]
]
