const underworld = [
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	],
	[
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		],
		[
			'^^^^^^^^^^^^^^^^^^',
			'<xxxxxxx  xxxxxxx>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<                >',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<x              x>',
			'<xxxxxxx  xxxxxxx>',
			'vvvvvvvvvvvvvvvvvv'
		]
	]
]
